### ISSUE TITLE
Spoilers down after landing but still, fails passing the checklist

### ISSUE THREAD

**Issue by fredrevol** [patrickl92/AudioChecklistSOPs#6]
Hi Patrick,
Great plugin which I use now on every flight, flying both the Zibo 738 and LevelUp 737. One item that fails every time is the spoilers down after landing/parking. Even when down the checklist fails and I have to pass manually. I tried to look into what could cause the issue but got stuck. Attached is the Xplane log.txt if that helps. Let me know if there's any other file you may need. Thanks,

Fred
[Log.txt](https://github.com/patrickl92/AudioChecklist/files/7953000/Log.txt)

**Comment by patrickl92** [comment]
Hi Fred,
how do you stow the Speedbrake? If you let the aircraft do it automatically by advancing the thrust levers, it actually does not put it in the down detent state. You have to move it forward yourself the last little bit. Can this be the issue?

**Comment by fredrevol** [comment]
I actually do both (advance the levers, then stow them back using the speedbrake levers). Somehow it doesn't seem to work. I'll do a quick flight tomorrow and see in details. Will let you know

**Comment by patrickl92** [comment]
Please also post a screenshot of the speedbrake if the checklist item fails

**Comment by fredrevol** [comment]
Very strange behaviour. Not sure why but the spoilers, suddenly get up after shutdown. See the full test flight I did:
https://youtu.be/0_PnowRCFzQ

The shutdown checklist is at the very end, I cut just after. Thanks for your heads-up.

Fred

**Comment by patrickl92** [comment]
Your video shows that the speedbrake lever is actually full forward, but it is not in the detent position. This is your state:

![Speedbrake_NotDetent](https://user-images.githubusercontent.com/16118262/151553799-08310349-0726-47a8-95f4-c250f60df641.png)

This is how it should look like:

![Speedbrake_Detent](https://user-images.githubusercontent.com/16118262/151553820-a8278659-c4bc-4998-8fa0-da9fbc2be7f5.png)

For me, clicking the speedbrake lever with the mouse moves it in the detent position after it was rectracted automatically. How do you deploy and stow the speedbrake (i.e. using the mouse, joystick button, joystick axis)?

https://user-images.githubusercontent.com/16118262/151554049-885bdd57-c3fd-44fc-bdd6-3ca469c37457.mp4

**Comment by patrickl92** [comment]
Just got the information that the video I posted actually shows a bug in the Zibo Mod. The speedbrake lever should move in the detent position automatically. I guess it should also do that in your case.

**Comment by fredrevol** [comment]
Ah, got it. Let me raise it, let’s see.

 

Fred

**Comment by fredrevol** [comment]
Just completed a flight, I used the mouse to put the lever back into down detent. until this is fixed on the aircraft I'll do that. Closing this item. Thanks, for your help,
Fred
